signal_ratio: 0.01
n_3b: 50_000
ratio_4b: 0.5
seed: 42
base_fvt_train_ratio: 0.75
SR_train_ratio: 0.33
base_fvt:
  dim_dijet_features: 6
  dim_quadjet_features: 6 
  batch_size: 1024
  max_epochs: 20
  data_seed: 42
  train_seed: 42 
  val_ratio: 0.33
  lr: 0.001
SRCR:
  method: smearing
  noise_scale: 0.1
  4b_in_CR: 0.6
  4b_in_SR: 0.2
CR_fvt:
  dim_dijet_features: 6
  dim_quadjet_features: 6 
  batch_size: 1024
  max_epochs: 20
  data_seed: 42
  train_seed: 42 
  val_ratio: 0.33
  lr: 0.001







signal_filename: HH4b_picoAOD.h5
experiment_name: counting_test_v1_demo