signal_ratio: 0.01
dim_dijet_features: 6
dim_quadjet_features: 6 
n_3b: 40000
n_all4b: 40000
test_ratio: 0.2
val_ratio: 0.33
batch_size: 1024
max_epochs: 50
seeds: 
- 42
lr: 0.001
experiment_name: fvt_training_n_samples_pilot