signal_ratio: 0.01
dim_dijet_features: 6
dim_quadjet_features: 6 
n_3b: 200_0000
n_all4b: 220_0000
test_ratio: 0.2
val_ratio: 0.33
batch_size: 1024
max_epochs: 50
seeds: 
- 42
- 52
lr: 0.001
n_sample_ratios:
- 0.03125
- 0.0625
- 0.125
- 0.25
- 0.5
- 1.0
experiment_name: fvt_training_n_samples_1
