seed: 42
train_data_ratio: 0.8
use_gradients: false
sym_model_path: "/home/soheuny/HH4bsim/playground/fvt_fit/archive/FvT_ResNet_6_6_6_np799_lr0.01_epochs30_stdscale_epoch30_loss0.6706.pkl"
run_name_base: "naive_mlp_ae"
latent_dim: 2
hidden_dims: [256, 256, 256, 256]
lr: 0.001
batch_size: 1024
max_epochs: 50