beta: 0.2
decoder_config:
  hidden_dims:
  - 256
  - 256
  - 256
  - 256
  latent_dim: 4
  output_dim: 16
  type: MLPDecoder
encoder_activation: SiLU
encoder_config:
  dim_input_jet_features: 4
  dim_intermed_dijet_features: 256
  dim_intermed_quadjet_features: 128
  name: fvt
  type: FvTEncoder
input_dim: 16
latent_dim: 4
likelihood_configs:
- lb: 0
  type: TruncatedGaussian
- lb: 0
  type: TruncatedGaussian
- lb: 0
  type: TruncatedGaussian
- lb: 0
  type: TruncatedGaussian
- lb: -2.5
  type: TruncatedGaussian
  ub: 2.5
- lb: -2.5
  type: TruncatedGaussian
  ub: 2.5
- lb: -2.5
  type: TruncatedGaussian
  ub: 2.5
- lb: -2.5
  type: TruncatedGaussian
  ub: 2.5
- lb: -3.141592653589793
  type: TruncatedGaussian
  ub: 3.141592653589793
- lb: -3.141592653589793
  type: TruncatedGaussian
  ub: 3.141592653589793
- lb: -3.141592653589793
  type: TruncatedGaussian
  ub: 3.141592653589793
- lb: -3.141592653589793
  type: TruncatedGaussian
  ub: 3.141592653589793
- type: Gaussian
- type: Gaussian
- type: Gaussian
- type: Gaussian
lr: 0.001
run_name: fvt_vae_latent_dim=4_beta=0.2_lr=0.001
