#!/usr/bin/env python3
"""Materialise standalone figure scripts from the draft notebooks.

Each notebook cell that contributes to a manuscript figure is copied out verbatim
into run_files/figure_scripts/<key>.py. Only three things change:

  * cell 0 is dropped everywhere (it is the cwd assert + chdir boilerplate that the
    generated header replaces),
  * IPython magics are blanked and `display` becomes a no-op,
  * listed rewrites narrow sweeps to what the manuscript actually shows.

Re-run this after editing a notebook to refresh the scripts.
"""

import re
from pathlib import Path

import nbformat

REPO = Path("/home/export/soheuny/SRFinder/soheun")
OUT_DIR = REPO / "run_files/figure_scripts"

HEADER = '''#!/usr/bin/env python3
"""GENERATED by run_files/extract_figure_scripts.py -- do not edit by hand.

Source: {notebook} cells {cells}
Figures: {figures}
{note}
"""

import os
import sys

REPO = "/home/export/soheuny/SRFinder/soheun"
sys.path.insert(0, REPO)
os.chdir(REPO)

import matplotlib

matplotlib.use("Agg")


def display(*args, **kwargs):  # notebook shim
    return None


def get_ipython():  # notebook shim
    return None

'''

SPECS = [
    dict(
        key="toys",
        notebook="notebooks/draft/toys.ipynb",
        cells=[1, 2],
        figures=["smear_toy_updated.pdf"],
        note="Drops cells 3-9: three toy figures the manuscript does not use.",
    ),
    dict(
        key="classifier",
        notebook="notebooks/draft/classifier.ipynb",
        cells=[1, 2, 3, 4],
        figures=["classifier_example_hist_exp=smeared_fvt_training_ensemble_signal=0.01.pdf"],
        note="Drops cells 5-6: two further 100-seed sweeps for figures not in the manuscript.",
    ),
    dict(
        key="smearing",
        notebook="notebooks/draft/smearing.ipynb",
        cells=[1, 2, 3, 4, 6, 7, 8, 11, 12],
        figures=[
            "smearing_overlap_signal_ratio_0.0_seed_5.pdf",
            "base_and_CR_fvt_scores_hist_seed_5.pdf",
            "smearing_and_tails_signal_ratio_0.01_seed_50.pdf",
        ],
        note="Drops cell 5: how_smearing_works over 4 seeds, not in the manuscript.",
    ),
    dict(
        key="null_case",
        notebook="notebooks/draft/null_case.ipynb",
        cells=[1, 2, 3, 4, 5, 6, 7, 8],
        figures=["pull_vs_sr_stats_SR_size_0.2.pdf"],
        note=(
            "Drops cells 9-15: a 5-seed sweep for a figure not in the manuscript, plus "
            "the cells that raise KeyError on the missing n_reps=1000 aux_info key."
        ),
    ),
    dict(
        key="on_which_to_learn",
        notebook="notebooks/draft/on_which_to_learn.ipynb",
        cells=[1, 2, 3, 4, 5, 6, 7, 8],
        figures=["on_which_to_learn.pdf", "tsne_original_repr.pdf"],
        note="Whole notebook is needed; the t-SNE fit feeds the second figure.",
    ),
    dict(
        key="signal_concentration",
        notebook="notebooks/draft/signal_concentration.ipynb",
        cells=[1, 2, 3, 4, 5, 8],
        figures=[
            "4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.01_max_vs_mean_sr_stats_eta=inf.pdf",
            "4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.01_max_vs_mean_sr_stats_eta=2.0.pdf",
            "4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.01_different_noise_scales.pdf",
            "4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.02_different_noise_scales.pdf",
            "4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.01_vs_baseline.pdf",
            "4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.02_vs_baseline.pdf",
            "4b_vs_signal_exp=smeared_fvt_training_ensemble_HH4b_400_signal=0.0075_different_noise_scales.pdf",
            "4b_vs_signal_exp=smeared_fvt_training_ensemble_ZH4b_signal=0.03_different_noise_scales.pdf",
        ],
        note=(
            "Cells 4 and 5 are narrowed to the two signal ratios the manuscript shows; "
            "cell 8 already guards on its configs list. Cell 4 owns all four of its "
            "figures, so there is no separate eta=inf script."
        ),
        rewrites=[
            (
                4,
                r"^signal_ratios = \[0\.02, 0\.01, 0\.0075, 0\.005\]$",
                "signal_ratios = [0.02, 0.01]  # [extracted] narrowed to the manuscript",
            ),
            (
                5,
                r"^signal_ratios = \[0\.02, 0\.01, 0\.0075, 0\.005\]$",
                "signal_ratios = [0.02, 0.01]  # [extracted] narrowed to the manuscript",
            ),
        ],
    ),
]

MAGIC = re.compile(r"^\s*[%!]")


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "__init__.py").write_text("")
    for spec in SPECS:
        notebook = nbformat.read(REPO / spec["notebook"], as_version=4)
        chunks = [
            HEADER.format(
                notebook=spec["notebook"],
                cells=spec["cells"],
                figures=", ".join(spec["figures"]),
                note=spec.get("note", ""),
            )
        ]
        for index in spec["cells"]:
            cell = notebook.cells[index]
            if cell.cell_type != "code":
                continue
            source = "\n".join(
                "" if MAGIC.match(line) else line for line in cell.source.splitlines()
            )
            for cell_index, pattern, replacement in spec.get("rewrites", []):
                if cell_index == index:
                    source, n = re.subn(pattern, replacement, source, flags=re.MULTILINE)
                    if n == 0:
                        raise SystemExit(
                            f"{spec['key']}: rewrite for cell {index} matched nothing: {pattern!r}"
                        )
            chunks.append(f"\n# ---------------- cell {index} ----------------\n{source}\n")
        chunks.append(
            "\nprint('done: " + spec["key"] + "', flush=True)\n"
        )
        path = OUT_DIR / f"{spec['key']}.py"
        path.write_text("\n".join(chunks))
        lines = len(path.read_text().splitlines())
        print(f"wrote {path.relative_to(REPO)}  ({lines} lines, {len(spec['figures'])} figure(s))")


if __name__ == "__main__":
    main()
