experiment_name: better_fvt_training
signal_filename: HH4b_picoAOD.h5
signal_ratio: 0.0
n_3b: 100_0000
ratio_4b: 0.5
seed: 0
base_fvt_train_ratio: 0.75
base_fvt:
  dim_dijet_features: 6
  dim_quadjet_features: 6 
  batch_size: 4096
  fit_batch_size: True
  max_epochs: 50
  data_seed: 0
  train_seed: 0 
  val_ratio: 0.33
  early_stop_patience: null
  optimizer:
    type: Adam
    lr: 0.001
  lr_scheduler:
    type: ReduceLROnPlateau
    factor: 0.25
    threshold: 0.0001
    patience: 3
    cooldown: 1
    min_lr: 0.00005