device: !!python/object/apply:torch.device
- cuda
- 0
dim_dijet_features: 6
dim_input_jet_features: 4
dim_quadjet_features: 6
lr: 0.001
num_classes: 2
run_name: fvt_picoAOD_signal_ratio=0.05_dijet=6_quadjet=6_n_3b=250000_n_all4b=250000_epochs=50_seed=42_sb_signal_region_ratio=0.3_probs_4b_threshold=0.7_pick_high_ratio_4b_exceeded_discard_failed
