#!/usr/bin/env python3
"""GENERATED by run_files/extract_figure_scripts.py -- do not edit by hand.

Source: notebooks/draft/classifier.ipynb cells [1, 2, 3, 4]
Figures: classifier_example_hist_exp=smeared_fvt_training_ensemble_signal=0.01.pdf
Drops cells 5-6: two further 100-seed sweeps for figures not in the manuscript.
"""

import os
import sys

REPO = "/home/export/soheuny/SRFinder/soheun"
sys.path.insert(0, REPO)
os.chdir(REPO)

import matplotlib

matplotlib.use("Agg")


def display(*args, **kwargs):  # notebook shim
    return None


def get_ipython():  # notebook shim
    return None



# ---------------- cell 1 ----------------
from typing import Tuple, Any
from constants import FEATURES
from signal_region import compute_sr_stats, get_SR_CR_cut
from events_data import events_from_scdinfo
from dataset import MotherSamples
from training_info import TrainingInfo
from events_data import EventsData

SIGNAL_FILENAME = "HH4b_picoAOD.h5"

def load_events_data(hash_: str) -> Tuple[Any, Any]:
    """Load training and test events data from a hash."""
    CR_fvt_tinfo = TrainingInfo.load(hash_)
    SR_stats_hashes = CR_fvt_tinfo.hparams["signal_region"]["SR_stats_hashes"]
    smeared_tinfo = TrainingInfo.load(SR_stats_hashes[0])
    msamples = MotherSamples.load(smeared_tinfo.ms_hash)
    
    events_train = events_from_scdinfo(
        msamples.scdinfo[smeared_tinfo.ms_idx], 
        FEATURES, 
        SIGNAL_FILENAME
    )
    events_tst = events_from_scdinfo(
        msamples.scdinfo[~smeared_tinfo.ms_idx], 
        FEATURES, 
        SIGNAL_FILENAME
    )
    return events_train, events_tst


# ---------------- cell 2 ----------------
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from plots import hist_events_by_labels
from events_data import EventsData
from fvt_classifier import FvTClassifier
# import LogNorm
from matplotlib.colors import LogNorm
from training_info import TrainingInfo
from plots import plot_rewighted_samples_by_model, plot_samples_raw
from dataset import MotherSamples
from events_data import events_from_scdinfo
import pickle

features = [
    "sym_Jet0_pt", "sym_Jet1_pt", "sym_Jet2_pt", "sym_Jet3_pt",
    "sym_Jet0_eta", "sym_Jet1_eta", "sym_Jet2_eta", "sym_Jet3_eta",
    "sym_Jet0_phi", "sym_Jet1_phi", "sym_Jet2_phi", "sym_Jet3_phi",  
    "sym_Jet0_m", "sym_Jet1_m", "sym_Jet2_m", "sym_Jet3_m",
]

# use tex
plt.rcParams["text.usetex"] = True
plt.rcParams["font.family"] = "serif"
plt.rcParams["text.latex.preamble"] = r"\usepackage{newtxtext}\usepackage{newtxmath}"

plt.rcParams["figure.dpi"] = 100
plt.rcParams["figure.titlesize"] = 20
plt.rcParams["axes.titlesize"] = 20
plt.rcParams["axes.labelsize"] = 15
plt.rcParams["xtick.labelsize"] = 15
plt.rcParams["ytick.labelsize"] = 15
plt.rcParams["figure.labelsize"] = 20
plt.rcParams["lines.markersize"] = 3
# legend font size
plt.rcParams["legend.fontsize"] = 15

import pandas as pd

path_3b = Path("../events/MG3/dataframes/threeTag_picoAOD.h5")
path_4b = Path("../events/MG3/dataframes/fourTag_10x_picoAOD.h5")
path_signal = Path("../events/MG3/dataframes/HH4b_picoAOD.h5")
df_3b = pd.read_hdf(path_3b)
df_bg4b = pd.read_hdf(path_4b)
df_signal = pd.read_hdf(path_signal)
df_3b["signal"] = False
df_bg4b["signal"] = False
df_signal["signal"] = True
raw_df_list = [df_3b, df_bg4b, df_signal]
loaded_df = {path_3b: df_3b, path_4b: df_bg4b, path_signal: df_signal}


def get_events_tst(smeared_hash: str) -> EventsData:
    smeared_fvt_tinfo = TrainingInfo.load(smeared_hash)
        
    base_encoder_hash = smeared_fvt_tinfo.hparams["encoder_hash"]
    base_fvt_tinfo = TrainingInfo.load(base_encoder_hash)
    ms_hash = base_fvt_tinfo.ms_hash
    ms_idx = base_fvt_tinfo.ms_idx
    msamples = MotherSamples.load(ms_hash)
    tst_scdinfo = msamples.scdinfo[~ms_idx]
    df_tst = tst_scdinfo.fetch_data(loaded_df)
    events_tst = EventsData.from_dataframe(df_tst, features)
    return events_tst


# ---------------- cell 3 ----------------
def hist_events_by_labels_simple(events: EventsData, values: np.ndarray, bins: np.ndarray, ax: plt.Axes, **kwargs):
    hist_3b, bins, _ = ax.hist(
        values[events.is_3b],
        bins=bins,
        histtype="step",
        label=labels["3b"],
        weights=events.weights[events.is_3b],
    )
    ax.hist(
        values[events.is_bg4b],
        bins=bins,
        histtype="step",
        label=labels["bg4b"],
        weights=events.weights[events.is_bg4b],
    )
    ax.hist(
        values[events.is_signal],
        bins=bins,
        histtype="step",
        label=labels["signal"],
        weights=events.weights[events.is_signal],
    )

plt.rcParams["axes.labelsize"] = 30
plt.rcParams["axes.titlesize"] = 30
plt.rcParams["legend.fontsize"] = 20
plt.rcParams["axes.titlepad"] = 10
plt.rcParams["xtick.labelsize"] = 20
plt.rcParams["ytick.labelsize"] = 20
plt.rcParams["figure.labelsize"] = 30


# ---------------- cell 4 ----------------
from plots import hist_events_by_labels
import tqdm

n_3b = 100_0000
seeds = range(1)
signal_ratio = 0.01
ensemble_seed = 0
noise_scale = 1.0

for experiment_name in [
    "smeared_fvt_training_ensemble",
    # "smeared_fvt_training_ensemble_HH4b_400",
    # "smeared_fvt_training_ensemble_HH4b_800"
    ]:
    
    print(experiment_name)
    for seed in tqdm.tqdm(seeds):
        hashes, hparams = TrainingInfo.find({"experiment_name": experiment_name, 
                                            "dataset": lambda x: (x["signal_ratio"] == signal_ratio 
                                                                and x["seed"] == seed 
                                                                and x["n_3b"] == n_3b), 
                                            "smearing": lambda x: x["noise_scale"] == noise_scale
                                            }, return_hparams=True, use_cached_metadata=True)
        
        failed_seed = 0
        success_seed = 2
        
        
        fig, ax = plt.subplots(1, 2, figsize=(15, 5), sharex=True, sharey="row")
        
        for i, seed in enumerate([success_seed, failed_seed]):
            hash_ = hashes[seed]
            smeared_fvt_tinfo = TrainingInfo.load(hash_)
            base_hash = smeared_fvt_tinfo.hparams["encoder_hash"]
            base_fvt_tinfo = TrainingInfo.load(base_hash)
            base_fvt_logit = base_fvt_tinfo.aux_info["base_fvt_logit_tst"]
            base_fvt_score = np.exp(base_fvt_logit) / (1 + np.exp(base_fvt_logit))
            events_tst = get_events_tst(hash_)
            labels = {"3b": r"$3b$", "bg4b": rf"Background $4b$", "signal": r"$\mathrm{HH} \to 4b$"}
            hist_events_by_labels_simple(events_tst, base_fvt_score, bins=np.linspace(0, 1, 100), ax=ax[i], 
                                  density=False, labels=labels)
            # hist_events_by_labels_simple(events_tst, base_fvt_score, bins=np.linspace(0, 1, 100), ax=ax[1, i], 
            #                       density=True, labels=labels)
        
        for a in ax.flatten():
            a.legend(loc="upper left")
            a.set_yscale("log")
            xmax = a.get_xlim()[1]
            a.set_xlim(0, xmax)
            
        fig.supxlabel("Classifier output")
        ax[0].set_ylabel("Counts")

        fig.text(0.325, 0.965, "Signal events captured", ha="center", va="top", fontsize=25)
        fig.text(0.73, 0.965, "Signal events not captured", ha="center", va="top", fontsize=25)

        # Shared legend just below the headers
        h, l = ax[0].get_legend_handles_labels()
        fig.legend(h, l,
           loc="upper center",
           bbox_to_anchor=(0.53, 0.935),  # (x,y) relative position in figure coords
           ncol=3,
           frameon=False)
        
        # Remove per-axes legends
        for a in ax.ravel():
            leg = a.get_legend()
            if leg is not None:
                leg.remove()

        plt.tight_layout(rect=[0.06, 0.06, 0.94, 0.86])
        plt.savefig(f"./figures/classifier_example_hist_exp={experiment_name}_signal={signal_ratio}.pdf", dpi=300)
        plt.show()
        plt.close()


print('done: classifier', flush=True)
