#!/usr/bin/env python3
"""GENERATED by run_files/extract_figure_scripts.py -- do not edit by hand.

Source: notebooks/draft/null_case.ipynb cells [1, 2, 3, 4, 5, 6, 7, 8]
Figures: pull_vs_sr_stats_SR_size_0.2.pdf
Drops cells 9-15: a 5-seed sweep for a figure not in the manuscript, plus the cells that raise KeyError on the missing n_reps=1000 aux_info key.
"""

import os
import sys

REPO = "/home/export/soheuny/SRFinder/soheun"
sys.path.insert(0, REPO)
os.chdir(REPO)

import matplotlib

matplotlib.use("Agg")


def display(*args, **kwargs):  # notebook shim
    return None


def get_ipython():  # notebook shim
    return None



# ---------------- cell 1 ----------------
from typing import Tuple, Any
from constants import FEATURES
from signal_region import compute_sr_stats, get_SR_CR_cut
from events_data import events_from_scdinfo
from dataset import MotherSamples
from training_info import TrainingInfo

SIGNAL_FILENAME = "HH4b_picoAOD.h5"

def load_events_data(hash_: str) -> Tuple[Any, Any]:
    """Load training and test events data from a hash."""
    CR_fvt_tinfo = TrainingInfo.load(hash_)
    SR_stats_hashes = CR_fvt_tinfo.hparams["signal_region"]["SR_stats_hashes"]
    smeared_tinfo = TrainingInfo.load(SR_stats_hashes[0])
    msamples = MotherSamples.load(smeared_tinfo.ms_hash)
    
    events_train = events_from_scdinfo(
        msamples.scdinfo[smeared_tinfo.ms_idx], 
        FEATURES, 
        SIGNAL_FILENAME
    )
    events_tst = events_from_scdinfo(
        msamples.scdinfo[~smeared_tinfo.ms_idx], 
        FEATURES, 
        SIGNAL_FILENAME
    )
    return events_train, events_tst


# ---------------- cell 2 ----------------
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from plots import hist_events_by_labels
from events_data import EventsData
from fvt_classifier import FvTClassifier
# import LogNorm
from matplotlib.colors import LogNorm
from training_info import TrainingInfo
from plots import plot_rewighted_samples_by_model, plot_samples_raw
from dataset import MotherSamples
from events_data import events_from_scdinfo
import pickle

features = [
    "sym_Jet0_pt", "sym_Jet1_pt", "sym_Jet2_pt", "sym_Jet3_pt",
    "sym_Jet0_eta", "sym_Jet1_eta", "sym_Jet2_eta", "sym_Jet3_eta",
    "sym_Jet0_phi", "sym_Jet1_phi", "sym_Jet2_phi", "sym_Jet3_phi",  
    "sym_Jet0_m", "sym_Jet1_m", "sym_Jet2_m", "sym_Jet3_m",
]

# use tex
plt.rcParams["text.usetex"] = True
plt.rcParams["font.family"] = "serif"
plt.rcParams["text.latex.preamble"] = r"\usepackage{newtxtext}\usepackage{newtxmath}"

plt.rcParams["figure.dpi"] = 300
plt.rcParams["figure.titlesize"] = 20
plt.rcParams["axes.titlesize"] = 20
plt.rcParams["axes.labelsize"] = 15
plt.rcParams["xtick.labelsize"] = 15
plt.rcParams["ytick.labelsize"] = 15
plt.rcParams["figure.labelsize"] = 20
plt.rcParams["lines.markersize"] = 3
# legend font size
plt.rcParams["legend.fontsize"] = 15

import pandas as pd

path_3b = Path("../events/MG3/dataframes/threeTag_picoAOD.h5")
path_4b = Path("../events/MG3/dataframes/fourTag_10x_picoAOD.h5")
path_signal = Path("../events/MG3/dataframes/HH4b_picoAOD.h5")
df_3b = pd.read_hdf(path_3b)
df_bg4b = pd.read_hdf(path_4b)
df_signal = pd.read_hdf(path_signal)
df_3b["signal"] = False
df_bg4b["signal"] = False
df_signal["signal"] = True
raw_df_list = [df_3b, df_bg4b, df_signal]
loaded_df = {path_3b: df_3b, path_4b: df_bg4b, path_signal: df_signal}


# ---------------- cell 3 ----------------
experiment_name = "CR_fvt_training_ensemble_max"
hparams_filter = {
    "dataset": lambda x: (
        x["n_3b"] == 100_0000, 
        x["ratio_4b"] == 0.5,
        x["signal_filename"] == "HH4b_picoAOD.h5",
    ), 
    "experiment_name": experiment_name
}
hashes, hparams = TrainingInfo.find(hparams_filter, return_hparams=True)
metadata = TrainingInfo.load_cached_metadata()
existing = []
for hp in hparams:
    ns = metadata[hp["signal_region"]["SR_stats_hashes"][0]]["smearing"]["noise_scale"]
    sr = hp["dataset"]["signal_ratio"]
    seed = hp["dataset"]["seed"]
    SR_size = hp["signal_region"]["4b_in_SR"]
    existing.append((ns, sr, seed, SR_size))


# ---------------- cell 4 ----------------
pull_dict = pickle.load(open("./data/pulls/pull_by_hashes_sr_stats_CR_fvt_training_ensemble_max.pkl", "rb"))

for hash in pull_dict:
    hparams = metadata[hash]
    signal_ratio = hparams["dataset"]["signal_ratio"]
    SR_size = hparams["signal_region"]["4b_in_SR"]    
    sr_stats_hash = hparams["signal_region"]["SR_stats_hashes"][0]
    sr_stats_type = hparams["signal_region"]["stats_type"]
    if sr_stats_type == "fvt":
        noise_scale = np.inf
    else:
        noise_scale = metadata[sr_stats_hash]["smearing"]["noise_scale"]
    
    for v in pull_dict[hash]:
        binning_mode = v["binning_mode"]
        nbins = v["nbins"]
        hists = v["hists"]
        hist_3b_rw = hists["3b_rw"]
        hist_3b_rw_sq = hists["3b_rw_sq"]
        hist_4b = hists["4b"]
        hist_4b_sq = hists["4b_sq"]
        var_o1 = hists["var_o1"]
        var_o2 = hists["var_o2"]
        hist_3b_o1 = hists["3b_corrected_o1"]
        hist_3b_o2 = hists["3b_corrected_o2"]
        hist_signal = hists["signal"]
        hist_bg4b = hists["bg4b"]
        
        if binning_mode == "train":
            var_o0 = hist_4b_sq + hist_3b_rw_sq
        else:
            var_o0 = hist_4b_sq + hist_3b_rw_sq / nbins**2

        v["signal_ratio"] = signal_ratio
        v["SR_size"] = SR_size
        v["noise_scale"] = noise_scale
        v["pull_o0"] = (hist_4b - hist_3b_rw) / np.sqrt(var_o0)
        v["pull_o1"] = (hist_4b - hist_3b_o1) / np.sqrt(var_o1)
        v["pull_o2"] = (hist_4b - hist_3b_o2) / np.sqrt(var_o2)
        v["pull_signal"] = hist_signal / np.sqrt(var_o0)
        v["pull_bg4b"] = (hist_bg4b - hist_3b_rw) / np.sqrt(var_o0)


# ---------------- cell 5 ----------------
nbins_list = [32, 64]
pull_dict_as_list = []
for d in pull_dict.values():
    pull_dict_as_list.extend(d)


# ---------------- cell 6 ----------------
SR_sizes = [0.2]
signal_ratios = [0.0]
binning_modes = ["train"]
noise_scales = [0.5, 1.0, 2.0, 3.0, np.inf]

for SR_size in SR_sizes:
    for signal_ratio in signal_ratios:
        for binning_mode in binning_modes:
            for noise_scale in noise_scales:
                fig, ax = plt.subplots(2, len(nbins_list), figsize=(len(nbins_list) * 4, 5))
                fig.suptitle(f"Using " + r"$\widehat\psi$" + f" SR_size: {SR_size}, signal_ratio: {signal_ratio}, binning_mode: {binning_mode}, noise_scale: {noise_scale}")
                fig.supxlabel("Quantile of " + r"$\widehat\psi$")
                fig.supylabel("pull")
                tmp_dicts_target = [d for d in pull_dict_as_list if d["SR_size"] == SR_size 
                            and d["signal_ratio"] == signal_ratio
                            and d["binning_mode"] == binning_mode
                            and d["noise_scale"] == noise_scale]
                
                for nbins, ax_idx in zip(nbins_list, range(len(nbins_list))):
                    tmp_dicts = [d for d in tmp_dicts_target if d["nbins"] == nbins]
                    
                    pull_signal_mean = np.mean([d["pull_signal"] for d in tmp_dicts], axis=0)
                    pull_signal_std = np.std([d["pull_signal"] for d in tmp_dicts], axis=0)
                    
                    pull_bg4b_mean = np.mean([d["pull_bg4b"] for d in tmp_dicts], axis=0)
                    pull_bg4b_std = np.std([d["pull_bg4b"] for d in tmp_dicts], axis=0)
                    
                    pull_mean = np.mean([d["pull_o0"] for d in tmp_dicts], axis=0)
                    pull_std = np.std([d["pull_o0"] for d in tmp_dicts], axis=0)
                    
                    pull_mean_corrected_1 = np.mean([d["pull_o1"] for d in tmp_dicts], axis=0)
                    pull_std_corrected_1 = np.std([d["pull_o1"] for d in tmp_dicts], axis=0)
                    
                    pull_mean_corrected_2 = np.mean([d["pull_o2"] for d in tmp_dicts], axis=0)
                    pull_std_corrected_2 = np.std([d["pull_o2"] for d in tmp_dicts], axis=0)
                    
                    
                    current_ax_0 = ax[0, ax_idx]
                    current_ax_0.set_title(f"nbins: {nbins}")
                    bins = np.arange(nbins)
                    current_ax_0.errorbar(bins, pull_mean, yerr=pull_std, label="(4b - 3b rw) / std", capsize=3, fmt="o")
                    current_ax_0.errorbar(bins, pull_bg4b_mean, yerr=pull_bg4b_std, label="(bg4b - 3b rw) / std", capsize=3, fmt="o", 
                                        color=plt.get_cmap("tab10").colors[1])
                    current_ax_0.errorbar(bins, pull_signal_mean, yerr=pull_signal_std, label="signal / std", capsize=3, fmt="o", 
                                        color=plt.get_cmap("tab10").colors[2])
                    current_ax_0.axhline(0, color="black", linestyle="--")
                    current_ax_0.legend(fontsize=10)
                    current_ax_0.set_ylim(-1, 4)
                    
                    current_ax_1 = ax[1, ax_idx]
                    current_ax_1.errorbar(bins, pull_mean, yerr=pull_std, label="uncorrected", capsize=3, fmt="o", 
                                        color=plt.get_cmap("tab10").colors[0])
                    current_ax_1.errorbar(bins, pull_mean_corrected_1, yerr=pull_std_corrected_1, label="corrected (order 1)", capsize=3, fmt="o", 
                                        color=plt.get_cmap("tab10").colors[3])
                    current_ax_1.errorbar(bins, pull_mean_corrected_2, yerr=pull_std_corrected_2, label="corrected (order 2)", capsize=3, fmt="o", 
                                        color=plt.get_cmap("tab10").colors[4])
                    current_ax_1.axhline(0, color="black", linestyle="--")
                    current_ax_1.legend(fontsize=10)
                    current_ax_1.set_ylim(-1, 4)
                    
                plt.tight_layout()
                plt.show()
                
            colors = plt.get_cmap("tab10").colors


# ---------------- cell 7 ----------------
SR_sizes = [0.2]
signal_ratios = [0.0]
binning_modes = ["train"]
noise_scales = [np.inf]

for SR_size in SR_sizes:
    for signal_ratio in signal_ratios:
        for binning_mode in binning_modes:
            fig, ax = plt.subplots(len(nbins_list), 1, figsize=(6, len(nbins_list) * 4))
            fig.suptitle(f"Using FvT score, SR_size: {SR_size}, signal_ratio: {signal_ratio}")
            fig.supxlabel("bin index (FvT score)")
            fig.supylabel("pull")
            
            colors = plt.get_cmap("tab10").colors
            
            for nbins, ax_idx in zip(nbins_list, range(len(nbins_list))):
                for noise_idx, noise_scale in enumerate(noise_scales):
                    current_ax = ax[ax_idx]
                    smearing_str = "no smearing" if noise_scale == np.inf else f"smearing: {noise_scale}"
                    current_ax.set_title(f"nbins: {nbins}, {smearing_str}")
                    bins = np.arange(nbins)
                    
                    tmp_dicts = [d for d in pull_dict_as_list if d["SR_size"] == SR_size 
                                and d["signal_ratio"] == signal_ratio
                                and d["binning_mode"] == binning_mode
                                and d["noise_scale"] == noise_scale
                                and d["nbins"] == nbins]
                    
                    pull_signal_mean = np.mean([d["pull_signal"] for d in tmp_dicts], axis=0)
                    pull_signal_std = np.std([d["pull_signal"] for d in tmp_dicts], axis=0)
                    
                    pull_bg4b_mean = np.mean([d["pull_bg4b"] for d in tmp_dicts], axis=0)
                    pull_bg4b_std = np.std([d["pull_bg4b"] for d in tmp_dicts], axis=0)
                    
                    pull_mean = np.mean([d["pull_o0"] for d in tmp_dicts], axis=0)
                    pull_std = np.std([d["pull_o0"] for d in tmp_dicts], axis=0)
                    
                    current_ax.errorbar(bins, pull_mean, yerr=pull_std, 
                                      label="(4b - 3b rw) / std", 
                                      capsize=3, fmt="o", color=colors[0])
                    current_ax.errorbar(bins, pull_bg4b_mean, yerr=pull_bg4b_std, 
                                      label="(bg4b - 3b rw) / std", 
                                      capsize=3, fmt="o", color=colors[1])
                    current_ax.errorbar(bins, pull_signal_mean, yerr=pull_signal_std, 
                                      label="signal / std", 
                                      capsize=3, fmt="o", color=colors[2])
                    
                    current_ax.axhline(0, color="black", linestyle="--")
                    current_ax.legend()
                    current_ax.set_ylim(-1, 4)
                
            plt.tight_layout()
            plt.show()


# ---------------- cell 8 ----------------
SR_sizes = [0.2]
signal_ratios = [0.0]
binning_modes = ["train"]
noise_scales = [np.inf, 2.0]
nbins = 64

for SR_size in SR_sizes:
    for signal_ratio in signal_ratios:
        for binning_mode in binning_modes:
            fig, ax = plt.subplots(1, 2, figsize=(14, 4))
            fig.supxlabel("Quantile of " + r"$\widehat\psi$")
            fig.supylabel("Normalized difference")
            
            colors = plt.get_cmap("tab10").colors
            
            for noise_idx, noise_scale in enumerate(noise_scales):
                current_ax = ax[noise_idx]
                smearing_str = "$\eta = \infty$ ($\widehat\psi = \widehat\gamma$)" if noise_scale == np.inf else rf"$\eta = {noise_scale}$"
                current_ax.set_title(f"{smearing_str}")
                    
                tmp_dicts = [d for d in pull_dict_as_list if d["SR_size"] == SR_size 
                            and d["signal_ratio"] == signal_ratio
                            and d["binning_mode"] == binning_mode
                            and d["noise_scale"] == noise_scale
                            and d["nbins"] == nbins]
                
                pull_signal_mean = np.mean([d["pull_signal"] for d in tmp_dicts], axis=0)
                pull_signal_std = np.std([d["pull_signal"] for d in tmp_dicts], axis=0)
                
                pull_bg4b_mean = np.mean([d["pull_bg4b"] for d in tmp_dicts], axis=0)
                pull_bg4b_std = np.std([d["pull_bg4b"] for d in tmp_dicts], axis=0)
                
                pull_mean = np.mean([d["pull_o0"] for d in tmp_dicts], axis=0)
                pull_std = np.std([d["pull_o0"] for d in tmp_dicts], axis=0)
                
                current_ax.errorbar(np.arange(nbins) / nbins, pull_mean, yerr=pull_std, 
                                    # label="(4b - 3b rw) / std", 
                                    capsize=3, fmt="o", color=colors[0])
                
                current_ax.axhline(0, color="black", linestyle="--")
                # current_ax.legend()
                current_ax.set_ylim(-1, 4)
            
            plt.tight_layout()
            plt.savefig(f"./figures/pull_vs_sr_stats_SR_size_{SR_size}.pdf", dpi=300)
            plt.show()


print('done: null_case', flush=True)
