#!/usr/bin/env python3
"""GENERATED by run_files/extract_figure_scripts.py -- do not edit by hand.

Source: notebooks/draft/on_which_to_learn.ipynb cells [1, 2, 3, 4, 5, 6, 7, 8]
Figures: on_which_to_learn.pdf, tsne_original_repr.pdf
Whole notebook is needed; the t-SNE fit feeds the second figure.
"""

import os
import sys

REPO = "/home/export/soheuny/SRFinder/soheun"
sys.path.insert(0, REPO)
os.chdir(REPO)

import matplotlib

matplotlib.use("Agg")


def display(*args, **kwargs):  # notebook shim
    return None


def get_ipython():  # notebook shim
    return None



# ---------------- cell 1 ----------------
from typing import Tuple, Any
from constants import FEATURES
from signal_region import compute_sr_stats, get_SR_CR_cut
from events_data import events_from_scdinfo
from dataset import MotherSamples
from training_info import TrainingInfo
from events_data import EventsData

SIGNAL_FILENAME = "HH4b_picoAOD.h5"

def load_events_data(hash_: str) -> Tuple[Any, Any]:
    """Load training and test events data from a hash."""
    CR_fvt_tinfo = TrainingInfo.load(hash_)
    SR_stats_hashes = CR_fvt_tinfo.hparams["signal_region"]["SR_stats_hashes"]
    smeared_tinfo = TrainingInfo.load(SR_stats_hashes[0])
    msamples = MotherSamples.load(smeared_tinfo.ms_hash)
    
    events_train = events_from_scdinfo(
        msamples.scdinfo[smeared_tinfo.ms_idx], 
        FEATURES, 
        SIGNAL_FILENAME
    )
    events_tst = events_from_scdinfo(
        msamples.scdinfo[~smeared_tinfo.ms_idx], 
        FEATURES, 
        SIGNAL_FILENAME
    )
    return events_train, events_tst


# ---------------- cell 2 ----------------
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import matplotlib as mpl

# add near the top of your file (before plotting):
import logging
logging.getLogger("matplotlib").setLevel(logging.WARNING)  # suppress INFO font message

plt.rcParams["text.usetex"] = True
plt.rcParams["font.family"] = "serif"
plt.rcParams["text.latex.preamble"] = r"\usepackage{newtxtext}\usepackage{newtxmath}"
plt.rcParams['axes.labelsize'] = 30
plt.rcParams['figure.labelsize'] = 30
plt.rcParams['xtick.labelsize'] = 20
plt.rcParams['ytick.labelsize'] = 20
plt.rcParams['axes.titlesize'] = 25
plt.rcParams['axes.titleweight'] = 'bold'
plt.rcParams['legend.fontsize'] = 20
# plt.rcParams["font.serif"] = ["Times New Roman"]


# ---------------- cell 3 ----------------
from signal_region import get_SR_CR_cut, get_DRs
import pandas as pd
from utils import get_quantiles_with_weights
import torch
import matplotlib.pyplot as plt
import numpy as np
from plots import plot_rewighted_samples_by_model

features = FEATURES


n_3b = 100_0000
device = torch.device("cuda")
experiment_name = "CR_fvt_training_v2"
signal_filename = "HH4b_picoAOD.h5"
ratio_4b = 0.5
nbins = 16
signal_ratio = 0.02
seed = 1
CR_fvt_type = ["repr", "original"]

hparam_filter = {
    "experiment_name": experiment_name,
    "dataset": lambda x: all([x["seed"] == seed, 
                        x["n_3b"] == n_3b, 
                        x["signal_ratio"] == signal_ratio]),
    "aux_info_step": 3
}
hashes = TrainingInfo.find(hparam_filter)
assert len(hashes) == 2

CR_fvt_tinfos = [TrainingInfo.load(hash) for hash in hashes]
for tinfo in CR_fvt_tinfos:
    if tinfo.hparams["model"] == "AttentionClassifier":
        CR_repr_fvt_tinfo = tinfo
    elif tinfo.hparams["model"] == "FvTClassifier":
        CR_orig_fvt_tinfo = tinfo

assert CR_repr_fvt_tinfo.hparams["signal_region"] == CR_orig_fvt_tinfo.hparams["signal_region"]
    
smeared_fvt_hash = CR_orig_fvt_tinfo.hparams["smeared_fvt_hash"]
base_encoder_hash = CR_orig_fvt_tinfo.hparams["encoder_hash"]

base_fvt_model = TrainingInfo.load(base_encoder_hash).load_trained_model(
    CR_orig_fvt_tinfo.hparams["encoder_mode"]
)
base_fvt_model.eval()
base_fvt_model.to(torch.device("cuda"))

smeared_fvt_tinfo = TrainingInfo.load(smeared_fvt_hash)
smeared_fvt_model = smeared_fvt_tinfo.load_trained_model(
    CR_orig_fvt_tinfo.hparams["encoder_mode"]
)
smeared_fvt_model.eval()
smeared_fvt_model.to(torch.device("cuda"))

# Use the same mother samples and exclude ones used for training base & smeared FvT model
msamples = MotherSamples.load(smeared_fvt_tinfo.ms_hash)
tst_scdinfo = msamples.scdinfo[~smeared_fvt_tinfo.ms_idx]
SR_stats_train = smeared_fvt_tinfo.aux_info["SR_stats_train"]
SR_stats = smeared_fvt_tinfo.aux_info["SR_stats_tst"]
events_tst = events_from_scdinfo(tst_scdinfo, features, signal_filename)
events_train = events_from_scdinfo(msamples.scdinfo[smeared_fvt_tinfo.ms_idx], features, signal_filename)
SR_cut, CR_cut = get_SR_CR_cut(SR_stats_train, events_train, CR_orig_fvt_tinfo.hparams["signal_region"])

SR_idx = (SR_stats >= SR_cut)
CR_idx = (SR_stats >= CR_cut) & (SR_stats < SR_cut)

events_tst_SR = events_tst[SR_idx]
SR_stats_SR = SR_stats[SR_idx]

events_train_SR = events_train[SR_stats_train >= SR_cut]    
SR_stats_train_SR = SR_stats_train[SR_stats_train >= SR_cut]

q_repr_tst_SR, _ = base_fvt_model.representations(events_tst_SR.X_torch)
q_repr_train_SR, _ = base_fvt_model.representations(events_train_SR.X_torch)

import matplotlib.gridspec as gridspec

# --- Gridspec layout: top = original hists, bottom = ratios ---
fig = plt.figure(figsize=(18, 7))
gs = fig.add_gridspec(2, 2, height_ratios=[2, 1], hspace=0.1, wspace=0.25)

ax_top = [fig.add_subplot(gs[0, 0]), fig.add_subplot(gs[0, 1])]
ax_bot = [fig.add_subplot(gs[1, 0], sharex=ax_top[0]),
          fig.add_subplot(gs[1, 1], sharex=ax_top[1])]

fig.supxlabel(r"$\widehat{\psi}$")
ax_top[0].set_ylabel("Counts")
ax_bot[0].set_ylabel("Ratio")

for ax_cnt, CR_fvt_type in enumerate(["original", "repr"]):
    if ax_cnt == 0:
        ax_top[ax_cnt].set_ylabel("Counts")
    CR_fvt_tinfo = CR_repr_fvt_tinfo if CR_fvt_type == "repr" else CR_orig_fvt_tinfo
    CR_fvt_model = CR_fvt_tinfo.load_trained_model("best")
    CR_fvt_model.eval()
    CR_fvt_model.to(torch.device("cuda"))
    
    if CR_fvt_type == "repr":
        fvt_scores_SR = CR_fvt_model.predict(q_repr_tst_SR)[:, 1].detach().cpu().numpy()
        fvt_scores_SR_train = CR_fvt_model.predict(q_repr_train_SR)[:, 1].detach().cpu().numpy()
    else:
        fvt_scores_SR = CR_fvt_model.predict(events_tst_SR.X_torch)[:, 1].detach().cpu().numpy()
        fvt_scores_SR_train = CR_fvt_model.predict(events_train_SR.X_torch)[:, 1].detach().cpu().numpy()
        
    reweights_SR_train = fvt_scores_SR_train / (1 - fvt_scores_SR_train)
    reweights_SR_train = np.where(events_train_SR.is_4b, 1, reweights_SR_train)
    SR_bins = np.linspace(np.min(SR_stats_train_SR), np.max(SR_stats_train_SR), nbins + 1)
    # SR_bins = get_quantiles_with_weights(SR_stats_train_SR[events_train_SR.is_3b], 
    #                                     (reweights_SR_train * events_train_SR.weights)[events_train_SR.is_3b], 
    #                                     np.linspace(0, 1, nbins + 1))
        
    reweights_SR = fvt_scores_SR / (1 - fvt_scores_SR)
    reweights_SR = np.where(events_tst_SR.is_4b, 1, reweights_SR)
    
    current_ax = ax_top[ax_cnt]
    CR_fvt_type_str = r"the representation space ($\zeta$)" if CR_fvt_type == "repr" else r"the original space ($x$)"
    current_ax.set_title(rf"Learning on {CR_fvt_type_str}")
    plot_rewighted_samples_by_model(events_tst_SR, SR_stats_SR, fvt_scores_SR, 
                                    ax=current_ax, bins=SR_bins, disable_twin_ax=True, errorbar="3b")
    hist_bg4b, _ = np.histogram(SR_stats_SR[events_tst_SR.is_bg4b], bins=SR_bins, 
                                weights=events_tst_SR.weights[events_tst_SR.is_bg4b])
    hist_signal, _ = np.histogram(SR_stats_SR[events_tst_SR.is_signal], bins=SR_bins, 
                                  weights=events_tst_SR.weights[events_tst_SR.is_signal])
    hist_3b, _ = np.histogram(SR_stats_SR[events_tst_SR.is_3b], bins=SR_bins,   
                                weights=events_tst_SR.weights[events_tst_SR.is_3b])
    hist_rw3b, _ = np.histogram(SR_stats_SR[events_tst_SR.is_3b], bins=SR_bins,   
                                weights=(reweights_SR * events_tst_SR.weights)[events_tst_SR.is_3b])
    
    current_ax.stairs(hist_3b, SR_bins, label=r"$3b$", color=plt.cm.tab10(0), linestyle="--")
    current_ax.stairs(hist_bg4b, SR_bins, label=r"Background $4b$", color=plt.cm.tab10(1), linestyle="--")
    current_ax.stairs(hist_signal, SR_bins, label=r"$\mathrm{HH} \to 4b$", color=plt.cm.tab10(2))
    current_ax.legend(fontsize=17.5)
    current_ax.set_ylim(bottom=0, top=5500)
    
    eps = 1e-12
    ratio = hist_rw3b / hist_bg4b
    error = np.sqrt(hist_rw3b + hist_bg4b) / hist_bg4b
    centers = 0.5 * (SR_bins[:-1] + SR_bins[1:])
    ax_ratio = ax_bot[ax_cnt]

    # Step-style ratio curve
    ax_ratio.errorbar(centers, ratio, yerr=error, color="red", linewidth=1.2, label=r"Background $4b$ / $3b$", capsize=2, marker="o", markersize=2)
    ax_ratio.axhline(1.0, color="gray", linestyle=":", linewidth=1.0)
    ax_ratio.set_ylim(0.5, 1.5)

# Optional: hide x tick labels on the top row (since shared with bottom)
for a in ax_top:
    a.tick_params(labelbottom=False)
    
        
plt.savefig("./figures/on_which_to_learn.pdf", dpi=300)
plt.show()
plt.close("all")


# ---------------- cell 4 ----------------
from signal_region import get_SR_CR_cut, get_DRs
import pandas as pd
from utils import get_quantiles_with_weights
import torch
import matplotlib.pyplot as plt
import numpy as np
from plots import plot_rewighted_samples_by_model

features = FEATURES

plt.rcParams["legend.fontsize"] = 15
plt.rcParams["figure.titlesize"] = 25
plt.rcParams["axes.titlesize"] = 20
plt.rcParams["axes.labelsize"] = 20
# increase tick label size
plt.rcParams["xtick.labelsize"] = 15
plt.rcParams["ytick.labelsize"] = 15

n_3b = 100_0000
device = torch.device("cuda")
experiment_name = "CR_fvt_training_v2"
signal_filename = "HH4b_picoAOD.h5"
ratio_4b = 0.5
nbins = 16
signal_ratio = 0.02
seed = 1
CR_fvt_type = ["repr", "original"]

hparam_filter = {
    "experiment_name": experiment_name,
    "dataset": lambda x: all([x["seed"] == seed, 
                        x["n_3b"] == n_3b, 
                        x["signal_ratio"] == signal_ratio]),
    "aux_info_step": 3
}
hashes = TrainingInfo.find(hparam_filter)
assert len(hashes) == 2

CR_fvt_tinfos = [TrainingInfo.load(hash) for hash in hashes]
for tinfo in CR_fvt_tinfos:
    if tinfo.hparams["model"] == "AttentionClassifier":
        CR_repr_fvt_tinfo = tinfo
    elif tinfo.hparams["model"] == "FvTClassifier":
        CR_orig_fvt_tinfo = tinfo

assert CR_repr_fvt_tinfo.hparams["signal_region"] == CR_orig_fvt_tinfo.hparams["signal_region"]
    
smeared_fvt_hash = CR_orig_fvt_tinfo.hparams["smeared_fvt_hash"]
base_encoder_hash = CR_orig_fvt_tinfo.hparams["encoder_hash"]

base_fvt_model = TrainingInfo.load(base_encoder_hash).load_trained_model(
    CR_orig_fvt_tinfo.hparams["encoder_mode"]
)
base_fvt_model.eval()
base_fvt_model.to(torch.device("cuda"))

smeared_fvt_tinfo = TrainingInfo.load(smeared_fvt_hash)
smeared_fvt_model = smeared_fvt_tinfo.load_trained_model(
    CR_orig_fvt_tinfo.hparams["encoder_mode"]
)
smeared_fvt_model.eval()
smeared_fvt_model.to(torch.device("cuda"))

# Use the same mother samples and exclude ones used for training base & smeared FvT model
msamples = MotherSamples.load(smeared_fvt_tinfo.ms_hash)
tst_scdinfo = msamples.scdinfo[~smeared_fvt_tinfo.ms_idx]
SR_stats_train = smeared_fvt_tinfo.aux_info["SR_stats_train"]
SR_stats = smeared_fvt_tinfo.aux_info["SR_stats_tst"]
events_tst = events_from_scdinfo(tst_scdinfo, features, signal_filename)
events_train = events_from_scdinfo(msamples.scdinfo[smeared_fvt_tinfo.ms_idx], features, signal_filename)
SR_cut, CR_cut = get_SR_CR_cut(SR_stats_train, events_train, {"4b_in_SR": 0.05, "4b_in_CR": 0.95})

SR_idx = (SR_stats >= SR_cut)
CR_idx = (SR_stats >= CR_cut) & (SR_stats < SR_cut)

events_tst_CR = events_tst[CR_idx]
SR_stats_CR = SR_stats[CR_idx]


# ---------------- cell 5 ----------------
# random samples from events_tst_CR

random_idx = np.random.choice(np.arange(len(events_tst_CR)), size=20000, replace=False)
events_tst_CR_random = events_tst_CR[random_idx]
q_repr_CR, _ = base_fvt_model.representations(events_tst_CR_random.X_torch)
features_CR = events_tst_CR_random.X_torch


# ---------------- cell 6 ----------------
from sklearn.manifold import TSNE

tsne = TSNE(
    n_components=2,
    perplexity=20,        
    learning_rate="auto", 
    init="pca",           
    n_iter=500,          
    early_exaggeration=12,
    random_state=42,
    metric="euclidean"    
)
is_3b = events_tst_CR_random.is_3b
is_bg4b = events_tst_CR_random.is_bg4b
is_signal = events_tst_CR_random.is_signal


# ---------------- cell 7 ----------------
features_embedded = tsne.fit_transform(features_CR)
repr_embedded = tsne.fit_transform(q_repr_CR.reshape(-1, q_repr_CR.shape[1] * q_repr_CR.shape[2]))


# ---------------- cell 8 ----------------
fig, ax = plt.subplots(1, 2, figsize=(10, 5))

ax[0].set_title("t-SNE of the original space", fontsize=20)
# sample 1000 points from is_3b, is_bg4b
# is_3b_int = np.where(is_3b)[0]
# is_3b_sample = np.random.choice(is_3b_int, size=2000, replace=False)
# is_bg4b_int = np.where(is_bg4b)[0]
# is_bg4b_sample = np.random.choice(is_bg4b_int, size=2000, replace=False)
ax[0].scatter(features_embedded[is_3b, 0], features_embedded[is_3b, 1], label=r"$3b$", s=2, rasterized=True)
ax[0].scatter(features_embedded[is_bg4b, 0], features_embedded[is_bg4b, 1], label=r"Background $4b$", s=2, rasterized=True)
ax[0].scatter(features_embedded[is_signal, 0], features_embedded[is_signal, 1], label=r"$\mathrm{HH} \to 4b$", s=30, rasterized=True)
ax[0].legend(loc="lower right", fontsize=15)

ax[1].set_title("t-SNE of the representation space", fontsize=20)    
ax[1].scatter(repr_embedded[is_3b, 0], repr_embedded[is_3b, 1], label=r"$3b$", s=2, rasterized=True)
ax[1].scatter(repr_embedded[is_bg4b, 0], repr_embedded[is_bg4b, 1], label=r"Background $4b$", s=2, rasterized=True)
ax[1].scatter(repr_embedded[is_signal, 0], repr_embedded[is_signal, 1], label=r"$\mathrm{HH} \to 4b$", s=30, rasterized=True)
ax[1].legend(loc="lower right", fontsize=15)

plt.tight_layout()
plt.savefig("figures/tsne_original_repr.pdf", dpi=300)
plt.show()
plt.close("all")


print('done: on_which_to_learn', flush=True)
