#!/usr/bin/env python3
"""GENERATED by run_files/extract_figure_scripts.py -- do not edit by hand.

Source: notebooks/draft/signal_concentration.ipynb cells [1, 2, 3, 4, 5, 8]
Figures: 4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.01_max_vs_mean_sr_stats_eta=inf.pdf, 4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.01_max_vs_mean_sr_stats_eta=2.0.pdf, 4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.01_different_noise_scales.pdf, 4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.02_different_noise_scales.pdf, 4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.01_vs_baseline.pdf, 4b_vs_signal_exp=smeared_fvt_training_ensemble_signal=0.02_vs_baseline.pdf, 4b_vs_signal_exp=smeared_fvt_training_ensemble_HH4b_400_signal=0.0075_different_noise_scales.pdf, 4b_vs_signal_exp=smeared_fvt_training_ensemble_ZH4b_signal=0.03_different_noise_scales.pdf
Cells 4 and 5 are narrowed to the two signal ratios the manuscript shows; cell 8 already guards on its configs list. Cell 4 owns all four of its figures, so there is no separate eta=inf script.
"""

import os
import sys

REPO = "/home/export/soheuny/SRFinder/soheun"
sys.path.insert(0, REPO)
os.chdir(REPO)

import matplotlib

matplotlib.use("Agg")


def display(*args, **kwargs):  # notebook shim
    return None


def get_ipython():  # notebook shim
    return None



# ---------------- cell 1 ----------------
from typing import Tuple, Any
from constants import FEATURES
from signal_region import compute_sr_stats, get_SR_CR_cut
from events_data import events_from_scdinfo
from dataset import MotherSamples
from training_info import TrainingInfo

SIGNAL_FILENAME = "HH4b_picoAOD.h5"

def load_events_data(hash_: str) -> Tuple[Any, Any]:
    """Load training and test events data from a hash."""
    CR_fvt_tinfo = TrainingInfo.load(hash_)
    SR_stats_hashes = CR_fvt_tinfo.hparams["signal_region"]["SR_stats_hashes"]
    smeared_tinfo = TrainingInfo.load(SR_stats_hashes[0])
    msamples = MotherSamples.load(smeared_tinfo.ms_hash)
    
    events_train = events_from_scdinfo(
        msamples.scdinfo[smeared_tinfo.ms_idx], 
        FEATURES, 
        SIGNAL_FILENAME
    )
    events_tst = events_from_scdinfo(
        msamples.scdinfo[~smeared_tinfo.ms_idx], 
        FEATURES, 
        SIGNAL_FILENAME
    )
    return events_train, events_tst


# ---------------- cell 2 ----------------
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from plots import hist_events_by_labels
from events_data import EventsData
from fvt_classifier import FvTClassifier
# import LogNorm
from matplotlib.colors import LogNorm
from training_info import TrainingInfo
from plots import plot_rewighted_samples_by_model, plot_samples_raw
from dataset import MotherSamples
from events_data import events_from_scdinfo
import pickle

features = [
    "sym_Jet0_pt", "sym_Jet1_pt", "sym_Jet2_pt", "sym_Jet3_pt",
    "sym_Jet0_eta", "sym_Jet1_eta", "sym_Jet2_eta", "sym_Jet3_eta",
    "sym_Jet0_phi", "sym_Jet1_phi", "sym_Jet2_phi", "sym_Jet3_phi",  
    "sym_Jet0_m", "sym_Jet1_m", "sym_Jet2_m", "sym_Jet3_m",
]

# use tex
plt.rcParams["text.usetex"] = True
plt.rcParams["font.family"] = "serif"
plt.rcParams["text.latex.preamble"] = r"\usepackage{newtxtext}\usepackage{newtxmath}"

plt.rcParams["figure.dpi"] = 100
plt.rcParams["axes.labelsize"] = 30
plt.rcParams["axes.titlesize"] = 30
plt.rcParams["legend.fontsize"] = 20
plt.rcParams["axes.titlepad"] = 10
plt.rcParams["xtick.labelsize"] = 20
plt.rcParams["ytick.labelsize"] = 20

import pandas as pd

path_3b = Path("../events/MG3/dataframes/threeTag_picoAOD.h5")
path_4b = Path("../events/MG3/dataframes/fourTag_10x_picoAOD.h5")
path_signal = Path("../events/MG3/dataframes/HH4b_picoAOD.h5")
df_3b = pd.read_hdf(path_3b)
df_bg4b = pd.read_hdf(path_4b)
df_signal = pd.read_hdf(path_signal)
df_3b["signal"] = False
df_bg4b["signal"] = False
df_signal["signal"] = True
raw_df_list = [df_3b, df_bg4b, df_signal]
loaded_df = {path_3b: df_3b, path_4b: df_bg4b, path_signal: df_signal}


# ---------------- cell 3 ----------------
def plot_mean_and_fill_between_std(x, y_list, ax, **kwargs):
    y_mean = np.mean(y_list, axis=0)
    y_std = np.std(y_list, axis=0)
    ax.plot(x, y_mean, **kwargs)
    if "color" in kwargs:
        ax.fill_between(x, y_mean - y_std, y_mean + y_std, alpha=0.2, color=kwargs["color"])
    else:
        ax.fill_between(x, y_mean - y_std, y_mean + y_std, alpha=0.2)
        
def get_events_tst(smeared_hash: str):
    smeared_fvt_tinfo = TrainingInfo.load(smeared_hash)
        
    base_encoder_hash = smeared_fvt_tinfo.hparams["encoder_hash"]
    base_fvt_tinfo = TrainingInfo.load(base_encoder_hash)
    ms_hash = base_fvt_tinfo.ms_hash
    ms_idx = base_fvt_tinfo.ms_idx
    msamples = MotherSamples.load(ms_hash)
    tst_scdinfo = msamples.scdinfo[~ms_idx]
    df_tst = tst_scdinfo.fetch_data(loaded_df)
    events_tst = EventsData.from_dataframe(df_tst, features)
    return events_tst


# ---------------- cell 4 ----------------

from plots import get_weights_by_sr_stats
import tqdm
import figure_cache

n_3b = 100_0000
seeds = range(100)
signal_ratios = [0.02, 0.01]  # [extracted] narrowed to the manuscript
ensemble_seeds = range(15)
noise_scales = [0.5, 1.0, 2.0, 3.0]

for experiment_name in ["smeared_fvt_training_ensemble"]:
    for signal_ratio in signal_ratios:    
        w_4b_ratio_points = np.arange(0, 1.01, 0.01)
        _cache_key = figure_cache.key(
            "signal_concentration.sr_efficiency", experiment_name, signal_ratio, n_3b, list(seeds), list(ensemble_seeds), noise_scales
        )
        signal_in_sr_list_dict = figure_cache.load(_cache_key)
        if signal_in_sr_list_dict is None:
            signal_in_sr_list_dict = {"max_fvt": [], "mean_fvt": []}
            for noise_scale in noise_scales:
                signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"] = []
                signal_in_sr_list_dict[f"mean_sr_stats@{noise_scale}"] = []
        
            for seed in tqdm.tqdm(seeds):
                base_fvt_logit_list = []
                for noise_scale in noise_scales:
                    hashes, hparams = TrainingInfo.find({"experiment_name": experiment_name, 
                                                        "dataset": lambda x: (x["signal_ratio"] == signal_ratio 
                                                                            and x["seed"] == seed 
                                                                            and x["n_3b"] == n_3b), 
                                                        "smearing": lambda x: x["noise_scale"] == noise_scale
                                                        }, return_hparams=True, use_cached_metadata=True)
                    if len(hashes) != 15:
                        print(f"Expected 15 hashes, got {len(hashes)} for signal_ratio={signal_ratio}, seed={seed}, noise_scale={noise_scale}")
                
                    events_tst = get_events_tst(hashes[0])
                    SR_stats_list = []
                
                    for hash in hashes:
                        smeared_fvt_tinfo = TrainingInfo.load(hash)
                        base_hash = smeared_fvt_tinfo.hparams["encoder_hash"]
                        base_fvt_tinfo = TrainingInfo.load(base_hash)
                        smeared_fvt_logit = smeared_fvt_tinfo.aux_info["smeared_fvt_logit_tst"]
                        base_fvt_logit = base_fvt_tinfo.aux_info["base_fvt_logit_tst"]
                        SR_stats_list.append(base_fvt_logit - smeared_fvt_logit)
                    
                        if noise_scale == 1.0:
                            base_fvt_logit_list.append(base_fvt_logit)
                    
                    max_sr_stats = np.max(SR_stats_list, axis=0)
                    w_4b_ratio_SR_max, w_signal_ratio_SR_max = get_weights_by_sr_stats(events_tst, max_sr_stats)
                    w_signal_ratio_SR_max = np.interp(w_4b_ratio_points, w_4b_ratio_SR_max, w_signal_ratio_SR_max)
                    signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"].append(w_signal_ratio_SR_max)
                
                    mean_sr_stats = np.mean(SR_stats_list, axis=0)
                    w_4b_ratio_SR_mean, w_signal_ratio_SR_mean = get_weights_by_sr_stats(events_tst, mean_sr_stats)
                    w_signal_ratio_SR_mean = np.interp(w_4b_ratio_points, w_4b_ratio_SR_mean, w_signal_ratio_SR_mean)
                    signal_in_sr_list_dict[f"mean_sr_stats@{noise_scale}"].append(w_signal_ratio_SR_mean)
                
                if len(base_fvt_logit_list) != 15:
                    print(f"Expected 15 base_fvt_logit_list, got {len(base_fvt_logit_list)} for signal_ratio={signal_ratio}, seed={seed}")
                base_fvt_logit_max = np.max(base_fvt_logit_list, axis=0)
                w_4b_ratio_base_max, w_signal_ratio_base_max = get_weights_by_sr_stats(events_tst, base_fvt_logit_max)
                w_signal_ratio_base_max = np.interp(w_4b_ratio_points, w_4b_ratio_base_max, w_signal_ratio_base_max)
                signal_in_sr_list_dict["max_fvt"].append(w_signal_ratio_base_max)
            
                base_fvt_logit_mean = np.mean(base_fvt_logit_list, axis=0)
                w_4b_ratio_base_mean, w_signal_ratio_base_mean = get_weights_by_sr_stats(events_tst, base_fvt_logit_mean)
                w_signal_ratio_base_mean = np.interp(w_4b_ratio_points, w_4b_ratio_base_mean, w_signal_ratio_base_mean)
                signal_in_sr_list_dict["mean_fvt"].append(w_signal_ratio_base_mean)
            
            figure_cache.save(_cache_key, signal_in_sr_list_dict)

        fig, ax = plt.subplots(1, 1, figsize=(8, 6))
        for noise_scale in noise_scales:
            plot_mean_and_fill_between_std(w_4b_ratio_points, signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"], 
                                        ax, label=rf"$\eta={noise_scale}$", linestyle="--")
        plot_mean_and_fill_between_std(w_4b_ratio_points, signal_in_sr_list_dict["max_fvt"], ax, 
                                       label="$\eta = \infty$", linestyle="--")
        
        ax.set_title(rf"$\epsilon={signal_ratio}$")
        ax.legend(loc="lower right")
        ax.set_xlabel(r"$P_{4b}(\mathcal{X}_s)$")
        ax.set_ylabel(r"$S(\mathcal{X}_s)$")
        # ax.set_aspect("equal")
        
        plt.savefig(f"./figures/4b_vs_signal_exp={experiment_name}_signal={signal_ratio}_different_noise_scales.pdf", 
                    dpi=300, bbox_inches="tight")
        plt.show()
        plt.close()
        
        fig, ax = plt.subplots(1, 1, figsize=(8, 6))
        noise_scale = 2.0
        plot_mean_and_fill_between_std(w_4b_ratio_points, 
                                       signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"], 
                                        ax, label=rf"Maximum", linestyle="--")
        plot_mean_and_fill_between_std(w_4b_ratio_points, 
                                       signal_in_sr_list_dict[f"mean_sr_stats@{noise_scale}"], 
                                        ax, label=rf"Mean", linestyle="--")
        ax.set_title(rf"$\epsilon={signal_ratio}$, $\eta={noise_scale}$")
        ax.legend(loc="lower right")
        ax.set_xlabel(r"$P_{4b}(\mathcal{X}_s)$")
        ax.set_ylabel(r"$S(\mathcal{X}_s)$")
        # ax.set_aspect("equal")
        
        plt.savefig(f"./figures/4b_vs_signal_exp={experiment_name}_signal={signal_ratio}_max_vs_mean_sr_stats_eta={noise_scale}.pdf", 
                    dpi=300, bbox_inches="tight")
        plt.show()
        plt.close()
        
        fig, ax = plt.subplots(1, 1, figsize=(8, 6))
        plot_mean_and_fill_between_std(w_4b_ratio_points, 
                                       signal_in_sr_list_dict[f"max_fvt"], 
                                        ax, label=rf"Maximum", linestyle="--")
        plot_mean_and_fill_between_std(w_4b_ratio_points, 
                                       signal_in_sr_list_dict[f"mean_fvt"], 
                                        ax, label=rf"Mean", linestyle="--")
        ax.set_title(rf"$\epsilon={signal_ratio}$, $\eta=\infty\ (\widehat\psi = \widehat\gamma)$")
        ax.legend(loc="lower right")
        ax.set_xlabel(r"$P_{4b}(\mathcal{X}_s)$")
        ax.set_ylabel(r"$S(\mathcal{X}_s)$")
        # ax.set_aspect("equal")
        
        plt.savefig(f"./figures/4b_vs_signal_exp={experiment_name}_signal={signal_ratio}_max_vs_mean_sr_stats_eta={np.inf}.pdf", 
                    dpi=300, bbox_inches="tight")
        plt.show()
        plt.close()


# ---------------- cell 5 ----------------
import tqdm

from ancillary_features import get_closest_dijet_masses
from plots import get_weights_by_sr_stats
from training_info import TrainingInfo

import numpy as np
import matplotlib.pyplot as plt

noise_scale = 2.0
signal_ratios = [0.02, 0.01]  # [extracted] narrowed to the manuscript
seeds = range(100)
n_3b = 100_0000

for experiment_name in ["smeared_fvt_training_ensemble"]:
    for signal_ratio in signal_ratios:    
        w_4b_ratio_points = np.arange(0, 1.01, 0.01)
        signal_in_sr_list_dict = {}
        signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"] = []
        signal_in_sr_list_dict["baseline"] = []
        
        for seed in tqdm.tqdm(seeds):
            base_fvt_logit_list = []
            hashes, hparams = TrainingInfo.find({"experiment_name": experiment_name, 
                                                "dataset": lambda x: (x["signal_ratio"] == signal_ratio 
                                                                    and x["seed"] == seed 
                                                                    and x["n_3b"] == n_3b), 
                                                "smearing": lambda x: x["noise_scale"] == noise_scale
                                                }, return_hparams=True, use_cached_metadata=True)
            if len(hashes) != 15:
                print(f"Expected 15 hashes, got {len(hashes)} for signal_ratio={signal_ratio}, seed={seed}, noise_scale={noise_scale}")
            
            events_tst = get_events_tst(hashes[0])
            SR_stats_list = []
            
            for hash in hashes:
                smeared_fvt_tinfo = TrainingInfo.load(hash)
                base_hash = smeared_fvt_tinfo.hparams["encoder_hash"]
                base_fvt_tinfo = TrainingInfo.load(base_hash)
                smeared_fvt_logit = smeared_fvt_tinfo.aux_info["smeared_fvt_logit_tst"]
                base_fvt_logit = base_fvt_tinfo.aux_info["base_fvt_logit_tst"]
                SR_stats_list.append(base_fvt_logit - smeared_fvt_logit)
                
            max_sr_stats = np.max(SR_stats_list, axis=0)
            w_4b_ratio_SR_max, w_signal_ratio_SR_max = get_weights_by_sr_stats(events_tst, max_sr_stats)
            w_signal_ratio_SR_max = np.interp(w_4b_ratio_points, w_4b_ratio_SR_max, w_signal_ratio_SR_max)
            signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"].append(w_signal_ratio_SR_max)
                
            dm_0, dm_1 = get_closest_dijet_masses(events_tst.X_torch)
            dm_0, dm_1 = dm_0.numpy(), dm_1.numpy()
            m_H = 125
            SR_stats_dm = - np.sqrt((1 - m_H / dm_0)**2 + (1 - m_H / dm_1)**2)    
            w_4b_ratio_baseline, w_signal_ratio_baseline = get_weights_by_sr_stats(events_tst, SR_stats_dm)
            w_signal_ratio_baseline = np.interp(w_4b_ratio_points, w_4b_ratio_baseline, w_signal_ratio_baseline)
            signal_in_sr_list_dict["baseline"].append(w_signal_ratio_baseline)
        
        # Plot the results
        fig, ax = plt.subplots(1, 1, figsize=(8, 6))
        plot_mean_and_fill_between_std(w_4b_ratio_points, signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"], 
                                    ax, label=rf"$\widehat\psi$ with $\eta={noise_scale}$", linestyle="--", 
                                    color=plt.get_cmap("tab10").colors[3])
        plot_mean_and_fill_between_std(w_4b_ratio_points, signal_in_sr_list_dict["baseline"], ax, 
                                       label="Model-aware Benchmark", linestyle="--",
                                       color=plt.get_cmap("tab10").colors[0])
        
        ax.set_title(rf"$\epsilon={signal_ratio}$")
        ax.legend(loc="lower right")
        ax.set_xlabel(r"$P_{4b}(\mathcal{X}_s)$")
        ax.set_ylabel(r"$S(\mathcal{X}_s)$")
        
        plt.savefig(f"./figures/4b_vs_signal_exp={experiment_name}_signal={signal_ratio}_vs_baseline.pdf", 
                    dpi=300, bbox_inches="tight")
        plt.show()
        plt.close()


# ---------------- cell 8 ----------------
from plots import get_weights_by_sr_stats
import tqdm

n_3b = 100_0000
seeds = range(100)
signal_ratios = [0.03, 0.02, 0.01, 0.0075, 0.005]
# signal_ratios = [0.02]
ensemble_seeds = range(15)
noise_scales = [0.5, 1.0, 2.0, 3.0]
colors = {
    0.1: plt.get_cmap("tab10").colors[0],
    0.5: plt.get_cmap("tab10").colors[1],
    1.0: plt.get_cmap("tab10").colors[2],
    2.0: plt.get_cmap("tab10").colors[3],
    3.0: plt.get_cmap("tab10").colors[4],
    np.inf: plt.get_cmap("tab10").colors[5],
}

configs = [
    ("smeared_fvt_training_ensemble_HH4b_400", 0.0075),
    ("smeared_fvt_training_ensemble_ZH4b", 0.03),
]

for experiment_name in [
    "smeared_fvt_training_ensemble_HH4b_400",
    "smeared_fvt_training_ensemble_ZH4b", 
    ]:
    for signal_ratio in signal_ratios:    
        
        if (experiment_name, signal_ratio) not in configs:
            continue
        
        w_4b_ratio_points = np.arange(0, 1.01, 0.01)
        _cache_key = figure_cache.key(
            "signal_concentration.sr_efficiency", experiment_name, signal_ratio, n_3b, list(seeds), list(ensemble_seeds), noise_scales
        )
        signal_in_sr_list_dict = figure_cache.load(_cache_key)
        if signal_in_sr_list_dict is None:
            signal_in_sr_list_dict = {"max_fvt": [], "mean_fvt": []}
            for noise_scale in noise_scales:
                signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"] = []
                signal_in_sr_list_dict[f"mean_sr_stats@{noise_scale}"] = []
        
            for seed in tqdm.tqdm(seeds):
                base_fvt_logit_list = []
                for noise_scale in noise_scales:
                    hashes, hparams = TrainingInfo.find({"experiment_name": experiment_name, 
                                                        "dataset": lambda x: (x["signal_ratio"] == signal_ratio 
                                                                            and x["seed"] == seed 
                                                                            and x["n_3b"] == n_3b), 
                                                        "smearing": lambda x: x["noise_scale"] == noise_scale
                                                        }, return_hparams=True, use_cached_metadata=True)
                    if len(hashes) != 15:
                        print(f"Expected 15 hashes, got {len(hashes)} for signal_ratio={signal_ratio}, seed={seed}, noise_scale={noise_scale}")
                
                    events_tst = get_events_tst(hashes[0])
                    SR_stats_list = []
                
                    for hash in hashes:
                        smeared_fvt_tinfo = TrainingInfo.load(hash)
                        base_hash = smeared_fvt_tinfo.hparams["encoder_hash"]
                        base_fvt_tinfo = TrainingInfo.load(base_hash)
                        smeared_fvt_logit = smeared_fvt_tinfo.aux_info["smeared_fvt_logit_tst"]
                        base_fvt_logit = base_fvt_tinfo.aux_info["base_fvt_logit_tst"]
                        SR_stats_list.append(base_fvt_logit - smeared_fvt_logit)
                    
                        if noise_scale == 1.0:
                            base_fvt_logit_list.append(base_fvt_logit)
                    
                    max_sr_stats = np.max(SR_stats_list, axis=0)
                    w_4b_ratio_SR_max, w_signal_ratio_SR_max = get_weights_by_sr_stats(events_tst, max_sr_stats)
                    w_signal_ratio_SR_max = np.interp(w_4b_ratio_points, w_4b_ratio_SR_max, w_signal_ratio_SR_max)
                    signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"].append(w_signal_ratio_SR_max)
                
                    mean_sr_stats = np.mean(SR_stats_list, axis=0)
                    w_4b_ratio_SR_mean, w_signal_ratio_SR_mean = get_weights_by_sr_stats(events_tst, mean_sr_stats)
                    w_signal_ratio_SR_mean = np.interp(w_4b_ratio_points, w_4b_ratio_SR_mean, w_signal_ratio_SR_mean)
                    signal_in_sr_list_dict[f"mean_sr_stats@{noise_scale}"].append(w_signal_ratio_SR_mean)
                
                if len(base_fvt_logit_list) != 15:
                    print(f"Expected 15 base_fvt_logit_list, got {len(base_fvt_logit_list)} for signal_ratio={signal_ratio}, seed={seed}")
                base_fvt_logit_max = np.max(base_fvt_logit_list, axis=0)
                w_4b_ratio_base_max, w_signal_ratio_base_max = get_weights_by_sr_stats(events_tst, base_fvt_logit_max)
                w_signal_ratio_base_max = np.interp(w_4b_ratio_points, w_4b_ratio_base_max, w_signal_ratio_base_max)
                signal_in_sr_list_dict["max_fvt"].append(w_signal_ratio_base_max)
            
                base_fvt_logit_mean = np.mean(base_fvt_logit_list, axis=0)
                w_4b_ratio_base_mean, w_signal_ratio_base_mean = get_weights_by_sr_stats(events_tst, base_fvt_logit_mean)
                w_signal_ratio_base_mean = np.interp(w_4b_ratio_points, w_4b_ratio_base_mean, w_signal_ratio_base_mean)
                signal_in_sr_list_dict["mean_fvt"].append(w_signal_ratio_base_mean)
            
            figure_cache.save(_cache_key, signal_in_sr_list_dict)

        fig, ax = plt.subplots(1, 1, figsize=(8, 6))
        for noise_scale in noise_scales:
            plot_mean_and_fill_between_std(w_4b_ratio_points, signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"], 
                                        ax, label=rf"$\eta={noise_scale}$", linestyle="--", color=colors[noise_scale])
        plot_mean_and_fill_between_std(w_4b_ratio_points, signal_in_sr_list_dict["max_fvt"], ax, 
                                       label="$\eta = \infty$", linestyle="--", color=colors[np.inf])
        
        ax.set_title(rf"$\epsilon={signal_ratio}$")
        ax.legend(loc="lower right")
        ax.set_xlabel(r"$P_{4b}(\mathcal{X}_s)$")
        ax.set_ylabel(r"$S(\mathcal{X}_s)$")
        # ax.set_aspect("equal")
        
        plt.savefig(f"./figures/4b_vs_signal_exp={experiment_name}_signal={signal_ratio}_different_noise_scales.pdf", 
                    dpi=300, bbox_inches="tight")
        plt.show()
        plt.close()
        
        # fig, ax = plt.subplots(1, 1, figsize=(8, 6))
        # noise_scale = 2.0
        # plot_mean_and_fill_between_std(w_4b_ratio_points, 
        #                                signal_in_sr_list_dict[f"max_sr_stats@{noise_scale}"], 
        #                                 ax, label=rf"Maximum", linestyle="--")
        # plot_mean_and_fill_between_std(w_4b_ratio_points, 
        #                                signal_in_sr_list_dict[f"mean_sr_stats@{noise_scale}"], 
        #                                 ax, label=rf"Mean", linestyle="--")
        # ax.set_title(rf"$\epsilon={signal_ratio}, \eta={noise_scale}$")
        # ax.legend(loc="lower right")
        # ax.set_xlabel(r"$P_{4b}(\mathcal{X}_s)$")
        # ax.set_ylabel(r"$S(\mathcal{X}_s)$")
        # # ax.set_aspect("equal")
        
        # plt.savefig(f"./figures/4b_vs_signal_exp={experiment_name}_signal={signal_ratio}_max_vs_mean_sr_stats_eta={noise_scale}.pdf", 
        #             dpi=300, bbox_inches="tight")
        # plt.show()
        # plt.close()
        
        # fig, ax = plt.subplots(1, 1, figsize=(8, 6))
        # plot_mean_and_fill_between_std(w_4b_ratio_points, 
        #                                signal_in_sr_list_dict[f"max_fvt"], 
        #                                 ax, label=rf"Maximum", linestyle="--")
        # plot_mean_and_fill_between_std(w_4b_ratio_points, 
        #                                signal_in_sr_list_dict[f"mean_fvt"], 
        #                                 ax, label=rf"Mean", linestyle="--")
        # ax.set_title(rf"$\epsilon={signal_ratio}$, $\eta = \infty$")
        # ax.legend(loc="lower right")
        # ax.set_xlabel(r"$P_{4b}(\mathcal{X}_s)$")
        # ax.set_ylabel(r"$S(\mathcal{X}_s)$")
        # # ax.set_aspect("equal")
        
        # plt.savefig(f"./figures/4b_vs_signal_exp={experiment_name}_signal={signal_ratio}_max_vs_mean_sr_stats_eta={np.inf}.pdf", 
        #             dpi=300, bbox_inches="tight")
        # plt.show()
        # plt.close()


print('done: signal_concentration', flush=True)
