#!/usr/bin/env python3
"""GENERATED by run_files/extract_figure_scripts.py -- do not edit by hand.

Source: notebooks/draft/toys.ipynb cells [1, 2]
Figures: smear_toy_updated.pdf
Drops cells 3-9: three toy figures the manuscript does not use.
"""

import os
import sys

REPO = "/home/export/soheuny/SRFinder/soheun"
sys.path.insert(0, REPO)
os.chdir(REPO)

import matplotlib

matplotlib.use("Agg")


def display(*args, **kwargs):  # notebook shim
    return None


def get_ipython():  # notebook shim
    return None



# ---------------- cell 1 ----------------
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import matplotlib as mpl

plt.rcParams["text.usetex"] = True
plt.rcParams["font.family"] = "serif"
plt.rcParams["text.latex.preamble"] = r"\usepackage{newtxtext}\usepackage{newtxmath}"
# mpl.rcParams["text.latex.preamble"] = (
#     r'\usepackage{helvet}'
#     r'\usepackage{sansmath}'
#     r'\sansmath'
# )

plt.rcParams['axes.labelsize'] = 30
plt.rcParams['figure.labelsize'] = 30
plt.rcParams['xtick.labelsize'] = 20
plt.rcParams['ytick.labelsize'] = 20
plt.rcParams['axes.titlesize'] = 25
plt.rcParams['axes.titleweight'] = 'bold'
plt.rcParams['legend.fontsize'] = 20
plt.rcParams["font.serif"] = ["Times New Roman"]


# ---------------- cell 2 ----------------
plt.rcParams["axes.labelsize"] = 30
plt.rcParams["axes.titlesize"] = 30
plt.rcParams["legend.fontsize"] = 16
plt.rcParams["axes.titlepad"] = 10
plt.rcParams["xtick.labelsize"] = 20
plt.rcParams["ytick.labelsize"] = 20
plt.rcParams["figure.labelsize"] = 30


# P_3b: Gaussian distribution N(0, 1)
# P_4b: Gaussian distribution N(0.1, 1) 
# Signal: Gaussian distribution N(1, 0.1)


# Generate data
np.random.seed(0)
mu_3b, sigma_3b = -0.25, 4
mu_4b, sigma_4b = 0.25, 4
mu_s, sigma_s = 7, 0.5
smear_sigma = 2
smear_sigma_2 = 0.25

signal_ratio = 0.05
x = np.linspace(-15, 15, 10000)

pdf_P_3b = stats.norm.pdf(x, mu_3b, sigma_3b)
pdf_B_4b = stats.norm.pdf(x, mu_4b, sigma_4b)
pdf_signal = stats.norm.pdf(x, mu_s, sigma_s)
pdf_P_4b = (1 - signal_ratio) * pdf_B_4b + signal_ratio * pdf_signal

pdf_P_3b_smeared = stats.norm.pdf(x, mu_3b, np.sqrt(sigma_3b**2 + smear_sigma**2))
pdf_B_4b_smeared = stats.norm.pdf(x, mu_4b, np.sqrt(sigma_4b**2 + smear_sigma**2))
pdf_signal_smeared = stats.norm.pdf(x, mu_s, np.sqrt(sigma_s**2 + smear_sigma**2))
pdf_P_4b_smeared = (1 - signal_ratio) * pdf_B_4b_smeared + signal_ratio * pdf_signal_smeared

pdf_P_3b_smeared_2 = stats.norm.pdf(x, mu_3b, np.sqrt(sigma_3b**2 + smear_sigma_2**2))
pdf_B_4b_smeared_2 = stats.norm.pdf(x, mu_4b, np.sqrt(sigma_4b**2 + smear_sigma_2**2))
pdf_signal_smeared_2 = stats.norm.pdf(x, mu_s, np.sqrt(sigma_s**2 + smear_sigma_2**2))
pdf_P_4b_smeared_2 = (1 - signal_ratio) * pdf_B_4b_smeared_2 + signal_ratio * pdf_signal_smeared_2

grid = GridSpec(6, 2)
fig = plt.figure(figsize=(14, 8))
ax = fig.add_subplot(grid[:2, 0])
fig.supxlabel(r"$\zeta$")

xlim = (-15, 15)
ylim = (0, 0.11)

ax.set_xlim(xlim)
ax.plot(x, pdf_P_4b / pdf_P_3b, label=r"$\gamma$", color='blue')
for label in ax.get_yticklabels():
    label.set_color('blue')

ax2 = plt.gca().twinx()
ax2.set_ylim(ylim)   
ax2.axvline(mu_s, linestyle="--", color="k")
ax2.plot(x, pdf_P_3b, label=r"$p_{3b}$", color=plt.cm.tab10(0))
ax2.plot(x, pdf_P_4b, label=r"$p_{4b}$", color=plt.cm.tab10(1))
# ax2 tick labels to m color
for label in ax2.get_yticklabels():
    label.set_color("k")
    

handles, labels = ax.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()
ax.legend(handles + handles2, labels + labels2, loc='upper left')
ax.set_xticks([])
ax2.set_xticks([])
ax.set_ylim(0, 6.5)

ax = fig.add_subplot(grid[2:4, 0])
ax.set_xlim(xlim)
ax.plot(x, pdf_P_4b_smeared / pdf_P_3b_smeared, label=r"$\widetilde{\gamma}_L$", color="green")
for label in ax.get_yticklabels():
    label.set_color("green")
ax.set_xticks([])


ax2 = plt.gca().twinx()
ax2.set_ylim(ylim)
ax2.axvline(mu_s, linestyle="--", color="k")
ax2.plot(x, pdf_P_3b_smeared, label=r"$p_{3b} * K_L$", color=plt.cm.tab10(0), linestyle="--")
ax2.plot(x, pdf_P_4b_smeared, label=r"$p_{4b} * K_L$", color=plt.cm.tab10(1), linestyle="--")
for label in ax2.get_yticklabels():
    label.set_color("k")
ax.set_ylim(0, 6.5)

handles, labels = ax.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()
ax.legend(handles + handles2, labels + labels2, loc='upper left')

ax = fig.add_subplot(grid[4:, 0])
ax.set_xlim(xlim)
ax.plot(x, pdf_P_4b_smeared_2 / pdf_P_3b_smeared_2, label=r"$\widetilde{\gamma}_s$", color="deepskyblue")
for label in ax.get_yticklabels():
    label.set_color("deepskyblue")


ax2 = plt.gca().twinx()
ax2.set_ylim(ylim)
ax2.axvline(mu_s, linestyle="--", color="k")
ax2.plot(x, pdf_P_3b_smeared_2, label=r"$p_{3b} * K_s$", color=plt.cm.tab10(0), linestyle="--")
ax2.plot(x, pdf_P_4b_smeared_2, label=r"$p_{4b} * K_s$", color=plt.cm.tab10(1), linestyle="--")
for label in ax2.get_yticklabels():
    label.set_color("k")
ax.set_ylim(0, 6.5)

# merge ax and ax2 legends

handles, labels = ax.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()
ax.legend(handles + handles2, labels + labels2, loc='upper left')

ylim = (0, 6.5)

ax = fig.add_subplot(grid[0:2, 1])
ax.set_xlim(xlim)
ax.set_ylim(ylim)
ax.axvline(mu_s, linestyle="--", color="k")
ax.plot(x, pdf_P_4b / pdf_P_3b, label=r"$\gamma$", color='blue')
for label in ax.get_yticklabels():
    label.set_color('blue')
ax.legend(loc='upper left')
ax.set_xticks([])

ylim = (0, 2.4)
ax = fig.add_subplot(grid[2:4, 1])
ax.set_xlim(xlim)
ax.set_ylim(ylim)
ax.axvline(mu_s, linestyle="--", color="k")
ax.plot(x, (pdf_P_4b / pdf_P_3b) / (pdf_P_4b_smeared / pdf_P_3b_smeared), 
        label=r"$\gamma / \widetilde{\gamma}_L$", color='green')
for label in ax.get_yticklabels():
    label.set_color('green')
ax.legend(loc='upper left')
ax.set_xticks([])

ylim = (0, 2.4)
ax = fig.add_subplot(grid[4:, 1])
ax.set_xlim(xlim)
ax.set_ylim(ylim)
ax.axvline(mu_s, linestyle="--", color="k")
ax.plot(x, (pdf_P_4b / pdf_P_3b) / (pdf_P_4b_smeared_2 / pdf_P_3b_smeared_2), 
        label=r"$\gamma / \widetilde{\gamma}_s$", color='deepskyblue')
for label in ax.get_yticklabels():
    label.set_color('deepskyblue')
ax.legend(loc='upper left')

row_ax = fig.add_subplot(grid[0:2, :])  
row_ax.set_title(r"Original distributions", fontsize=30, fontweight="bold", pad=20)
row_ax.axis("off")

row_ax = fig.add_subplot(grid[2:4, :])  
row_ax.set_title(r"Smearing with an appropriate scale kernel $K_L$", fontsize=30, fontweight="bold", pad=20)
row_ax.axis("off")

row_ax = fig.add_subplot(grid[4:, :])  
row_ax.set_title(r"Smearing with a small scale kernel $K_S$", fontsize=30, fontweight="bold", pad=20)
row_ax.axis("off")

plt.tight_layout()
plt.savefig("figures/smear_toy_updated.pdf", dpi=300)
plt.show()
plt.close()


print('done: toys', flush=True)
