device: !!python/object/apply:torch.device
- cuda
- 0
dim_dijet_features: 6
dim_input_jet_features: 4
dim_quadjet_features: 6
lr: 0.001
num_classes: 2
run_name: fvt_picoAOD_signal_ratio=0.03_four_tag_ratio=0.5_dijet=6_quadjet=6_n_3b=50000_n_all4b=50000_epochs=50_batch_size=1024_val_ratio=0.33_test_ratio=0.5_seed=92
