beta: 0.5
decoder_config:
  hidden_dims:
  - 256
  - 256
  - 256
  - 256
  latent_dim: 4
  output_dim: 16
  type: MLPDecoder
encoder_activation: SiLU
encoder_config:
  hidden_dims:
  - 256
  - 256
  - 256
  input_dim: 16
  latent_dim: 256
  name: mlp
  type: MLPEncoder
input_dim: 16
latent_dim: 4
likelihood_configs:
- lb: 0
  type: TruncatedGaussian
- lb: 0
  type: TruncatedGaussian
- lb: 0
  type: TruncatedGaussian
- lb: 0
  type: TruncatedGaussian
- lb: 0
  type: TruncatedGaussian
  ub: 2.5
- lb: -2.5
  type: TruncatedGaussian
  ub: 2.5
- lb: -2.5
  type: TruncatedGaussian
  ub: 2.5
- lb: -2.5
  type: TruncatedGaussian
  ub: 2.5
- lb: 0
  type: TruncatedGaussian
  ub: 0.1
- lb: 0
  type: TruncatedGaussian
  ub: 3.141592653589793
- lb: -3.141592653589793
  type: TruncatedGaussian
  ub: 3.141592653589793
- lb: -3.141592653589793
  type: TruncatedGaussian
  ub: 3.141592653589793
- type: Gaussian
- type: Gaussian
- type: Gaussian
- type: Gaussian
lr: 0.0001
run_name: mlp_vae_latent_dim=4_beta=0.5_lr=0.0001
