device: !!python/object/apply:torch.device
- cuda
- 0
dim_dijet_features: 6
dim_input_jet_features: 4
dim_quadjet_features: 6
lr: 0.001
num_classes: 2
run_name: fvt_classifier_toy_signal_ratio_lam_0.05_dijet_6_quadjet_{dim_quadjet_features}
