beta: 0.5
decoder_config:
  hidden_dims:
  - 256
  - 256
  - 256
  - 256
  latent_dim: 4
  output_dim: 16
  type: MLPDecoder
encoder_activation: SiLU
encoder_config:
  hidden_dims:
  - 256
  - 256
  - 256
  input_dim: 16
  latent_dim: 256
  name: mlp
  type: MLPEncoder
input_dim: 16
latent_dim: 4
lr: 0.0001
run_name: MLPEncoder_vae_latent_dim=4_beta=0.5_lr=0.0001
